name: Get Issue comment
on:
  issues:
    types:
      - opened
      - edited
  issue_comment:
    types:
      - created
      - edited
      - deleted

jobs:
  issue-commented:
    name: comment
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:

    # - name: Find Comment
    #   uses: peter-evans/find-comment@v2
    #   id: fc
    #   with:
    #     issue-number: ${{ github.event.issue.number }}
    #     direction: last

    # - name: Output comment
    #   run: |
    #     echo ${{ steps.fc.outputs.comment-id }}
    #     echo ${{ steps.fc.outputs.comment-body }}
    #     echo ${{ steps.fc.outputs.comment-author }}

    - name: Output issue body
      id: get-issue-data
      run: |
        PR_URLS=$(echo "${{ github.event.issue.body }}" | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | sort -u)
        echo "::set-output name=pr-urls::$PR_URLS"
    
    - name: Echo Urls
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        echo ${{ steps.get-issue-data.outputs.pr-urls }}
        gh pr view ${{ steps.get-issue-data.outputs.pr-urls }} --json headRefName,headRepository