name: Get Issue comment
on:
  issues:
    types:
      - opened
      - edited
  issue_comment:
    types:
      - created
      - edited
      - deleted

jobs:
  issue-commented:
    name: comment
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:

    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.issue.number }}
        direction: last

    - name: Output comment
      run: |
        echo ${{ steps.fc.outputs.comment-id }}
        echo ${{ steps.fc.outputs.comment-body }}
        echo ${{ steps.fc.outputs.comment-author }}